INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('CH17AT1545', 'Maruti Suzuki Alto', 1, 'avis72@hotmail.com');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('CH19UX5726', 'Maruti Suzuki S-Presso', 1, 'miller.janet@gmail.com');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('CH14TH3941', 'Hyundai Santro', 1, 'cathrine14@schultz.info');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('CH17XP6994', 'Hyundai Santro', 1, 'runte.colton@gulgowski.com');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('UP12WP3391', 'Maruti Suzuki Ertiga', 1, 'ywunsch@kshlerin.biz');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('WB12CI4748', 'Maruti Suzuki Eeco', 1, 'pouros.eriberto@gmail.com');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('DL17JR1544', 'Maruti Suzuki Wagon R', 1, 'nikolaus.letitia@balistreri.com');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('CH16BE4904', 'Toyota Urban Cruiser Hyryder', 1, 'schulist.granville@gmail.com');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('CH16ZG3118', 'Toyota Urban Cruiser Hyryder', 1, 'gutkowski.rhiannon@dicki.biz');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('UP13PV7992', 'Maruti Suzuki S-Presso', 1, 'conroy.ben@ernser.info');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('WB15HA8168', 'Hyundai Santro', 1, 'breitenberg.willard@gmail.com');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('CH15OA6375', 'Maruti Suzuki Wagon R', 1, 'braxton.leuschke@bechtelar.info');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('WB18KS5595', 'Maruti Suzuki Alto', 1, 'mitchell.watsica@hotmail.com');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('CH14LA6282', 'Maruti Suzuki S-Presso', 1, 'gdurgan@gmail.com');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('CH14CN1966', 'Hyundai Santro', 1, 'jlittle@schuppe.com');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('HR14IF9096', 'Maruti Suzuki Ertiga', 1, 'kay.altenwerth@gmail.com');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('DL12XO5572', 'Maruti Suzuki Eeco', 1, 'feeney.jarrell@hintz.info');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('UP16SD4822', 'Maruti Suzuki Wagon R', 1, 'della.krajcik@bahringer.net');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('WB11QN7608', 'Maruti Suzuki Wagon R', 1, 'omayert@kunde.com');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('WB17YX7734', 'Maruti Suzuki Wagon R', 1, 'rodger.rogahn@hahn.com');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('HR13UI8692', 'Tata Tiago EV', 1, 'myra.weber@yahoo.com');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('UP12WJ2012', 'Tata Tigor EV', 2, 'randal.price@hintz.org');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('UP17DU4802', 'Tata Nexon EV Max', 2, 'eichmann.baron@sanford.com');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('CH13MK3589', 'Tata Tiago EV', 2, 'xbalistreri@yahoo.com');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('UP13YM2636', 'Tata Tigor EV', 2, 'klocko.sylvan@schuppe.com');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('WB18YR7123', 'Tata Nexon EV Max', 2, 'deckow.myrtle@gmail.com');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('CH14KU4061', 'Tata Tiago EV', 2, 'norberto.waters@yahoo.com');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('HR13LJ1541', 'Tata Tigor EV', 2, 'harmony.steuber@nikolaus.biz');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('HR17ID1935', 'Tata Nexon EV Max', 2, 'cronin.allie@yahoo.com');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('HR19DX1516', 'Tata Tiago EV', 2, 'jast.tito@yahoo.com');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('WB19MJ7559', 'TATA Nexon XZ', 2, 'qflatley@emard.com');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('WB13UB3550', 'TATA Nexon XM', 3, 'eldora.gorczany@hotmail.com');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('HR18JP9473', 'Mahindra Scorpio', 3, 'evan59@hotmail.com');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('CH17IN8423', 'Toyota Fortuner', 3, 'aurelie92@prosacco.com');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('CH15EC2264', 'TATA Nexon XZ', 3, 'cschiller@yahoo.com');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('UP11GQ9460', 'TATA Nexon XM', 3, 'damore.leora@yahoo.com');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('WB10KF7294', 'Mahindra Scorpio', 3, 'merl.nitzsche@yahoo.com');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('DL17OK5976', 'Toyota Fortuner', 3, 'ycruickshank@cummerata.com');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('HR10CP2006', 'TATA Nexon XZ', 3, 'jarrell00@maggio.com');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('WB19DL2482', 'TATA Nexon XM', 3, 'ttoy@robel.com');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('UP16MH9117', 'Mahindra Scorpio', 3, 'wilford.rath@huels.com');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('WB17AW2251', 'Toyota Fortuner', 3, 'lstiedemann@gmail.com');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('WB17KA5443', 'TATA Nexon XZ', 3, 'wdavis@gorczany.com');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('HR19PJ5848', 'TATA Nexon XM', 3, 'gulgowski.ernie@russel.biz');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('UP17IF4740', 'Mahindra Scorpio', 3, 'jack54@yahoo.com');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('CH15HQ6675', 'Toyota Fortuner', 3, 'quinn.cronin@grimes.biz');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('DL17KA7906', 'TATA Nexon XZ', 3, 'baby.mohr@kuhic.com');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('CH11KN6112', 'TATA Nexon XM', 3, 'yjohnston@gmail.com');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('HR12QO6598', 'Mahindra Scorpio', 3, 'sage.collins@hamill.biz');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('UP19RH4208', 'Toyota Fortuner', 3, 'delpha.nolan@crona.biz');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('HR13LK2227', 'Autorickshaw ', 3, 'mante.telly@hotmail.com');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('UP11CA4446', 'Autorickshaw ', 4, 'stiedemann.rhoda@hotmail.com');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('CH16IE5828', 'Autorickshaw ', 4, 'angela62@olson.org');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('DL12UP2698', 'Autorickshaw ', 4, 'keely.heller@romaguera.com');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('CH12UT4147', 'Autorickshaw ', 4, 'kaela.pfannerstill@yahoo.com');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('HR14LK4024', 'Autorickshaw ', 4, 'estella.cole@wilkinson.org');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('WB18BI1495', 'Autorickshaw ', 4, 'zetta38@yahoo.com');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('HR17PG4430', 'Autorickshaw ', 4, 'cruickshank.sterling@anderson.net');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('WB11HT9510', 'Autorickshaw ', 4, 'dkulas@crooks.com');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('CH13LV6855', 'Autorickshaw ', 4, 'gtorphy@rodriguez.info');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('WB16VY4168', 'Autorickshaw ', 4, 'sabryna21@yahoo.com');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('DL18UW4923', 'Autorickshaw ', 4, 'juvenal.ratke@kuvalis.biz');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('WB17EA1109', 'Autorickshaw ', 4, 'ivory.shields@hotmail.com');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('HR15MW5901', 'Autorickshaw ', 4, 'alycia.hoppe@aufderhar.com');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('UP19CL4097', 'Autorickshaw ', 4, 'grady.cooper@gmail.com');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('UP12OC7884', 'Autorickshaw ', 4, 'larkin.nolan@raynor.com');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('CH10VR3622', 'Autorickshaw ', 4, 'kathleen.brakus@yahoo.com');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('WB17UT5412', 'Autorickshaw ', 4, 'gaston40@yahoo.com');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('WB13DK8206', 'Autorickshaw ', 4, 'ganderson@kuphal.org');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('UP13UY9425', 'Autorickshaw ', 4, 'blangworth@hotmail.com');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('HR12TB8805', 'Autorickshaw ', 4, 'emile38@mraz.info');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('DL10VH6760', 'Autorickshaw ', 4, 'micheal.heller@gmail.com');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('WB13IQ6342', 'Autorickshaw ', 4, 'elvie78@hotmail.com');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('DL14CK5742', 'Autorickshaw ', 4, 'bernita81@yahoo.com');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('CH11TK5203', 'Autorickshaw ', 4, 'laura.breitenberg@kirlin.net');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('UP10AD4815', 'Autorickshaw ', 4, 'pbartoletti@hotmail.com');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('UP13SM8025', 'Autorickshaw ', 4, 'mna50@yahoo.com');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('UP14KY7444', 'Autorickshaw ', 4, 'iynas_asar15@yahoo.com');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('CH15VX5172', 'Autorickshaw ', 4, 'fatmh90@yahoo.com');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('HR11SU1128', 'Autorickshaw ', 4, 'rqyh_hazm32@gmail.com');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('CH16KA8884', 'Yamaha MT', 4, 'hsn_salm28@gmail.com');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('UP11UU4137', 'Royal Enfield Classic', 5, 'dana_aarf@gmail.com');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('UP17ZZ6651', 'Hero Splendor Plus', 5, 'aayh_slah16@hotmail.com');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('UP13GE1732', 'Yamaha MT', 5, 'iynas91@hotmail.com');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('HR14KM3363', 'Royal Enfield Classic', 5, 'zynb34@yahoo.com');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('HR10VE9850', 'Hero Splendor Plus', 5, 'hazm75@hotmail.com');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('DL14AJ9183', 'Yamaha MT', 5, 'aadm10@gmail.com');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('CH12DG5250', 'Royal Enfield Classic', 5, 'sayd18@gmail.com');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('HR14FG9772', 'Hero Splendor Plus', 5, 'rna40@gmail.com');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('CH18OY1825', 'Yamaha MT', 5, 'fryd.farwq80@yahoo.com');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('CH13BT5348', 'Royal Enfield Classic', 5, 'rbya75@gmail.com');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('WB13XN1760', 'Hero Splendor Plus', 5, 'mna_aqyl@hotmail.com');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('UP13UR3383', 'Yamaha MT', 5, 'abyr73@gmail.com');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('DL11BA9898', 'Royal Enfield Classic', 5, 'sayd_blal@yahoo.com');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('CH15UH6956', 'Hero Splendor Plus', 5, 'aadm.azyz17@hotmail.com');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('WB15OL9248', 'Yamaha MT', 5, 'salm_aashwr@gmail.com');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('DL12FB5290', 'Royal Enfield Classic', 5, 'asamh25@gmail.com');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('CH16TD5579', 'Hero Splendor Plus', 5, 'iyhab_aashwr69@yahoo.com');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('UP16PR9832', 'Yamaha MT', 5, 'hajr3@yahoo.com');
INSERT INTO vehicles (reg_no, vname,type_id,d_email) VALUES ('WB15HN9314', 'Royal Enfield Classic', 5, 'sayd_hashm15@hotmail.com');
